[package]
name = "rust_tracer" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Johan Nordström <cjs.nordstrom@gmail.com>"]

# [dependencies]
# nalgebra = "0.32.2"
